# Generated by Django 5.2.3 on 2025-06-20 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
                ('video_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=255)),
                ('format_type', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
